import { toCamelCase, toPascalCase } from "./compiler-utils.js";
import type { BindingEvent, CompiledViewResult } from "./tsx-view-compiler.js";

export interface BindingMapEventEntry {
  id: string;
  event: BindingEvent;
  actionId: string;
  chunk: string;
  handlerExport: string;
  preventDefault?: boolean;
}

export interface BindingMapListEntry {
  listId: string;
  keyAttr: string;
}

export interface BindingMapModuleSourceOptions {
  generatedBy: string;
  bindingMapImportPath: string;
  bindingMapConstName: string;
  bindingMapBuilderName: string;
  events: readonly BindingMapEventEntry[];
  lists: readonly BindingMapListEntry[];
}

export interface CompiledViewBindingInferenceOptions {
  actionChunkPath: string;
  inferActionId?: (bindingId: string) => string;
  inferHandlerExport?: (bindingId: string) => string;
  shouldPreventDefault?: (bindingId: string, event: BindingEvent) => boolean;
  listKeyAttr?: string;
}

export interface CompiledViewModuleSourceOptions {
  fileBasename: string;
  propsIdentifier: string;
  compiled: CompiledViewResult;
  bindingMapTypeImportPath: string;
  viewCompilerImportPath: string;
  bindingInference?: CompiledViewBindingInferenceOptions;
}

function renderBindingMapObjectLiteralSource(
  events: readonly BindingMapEventEntry[],
  lists: readonly BindingMapListEntry[],
): string {
  const eventEntries = [...events]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((entry) => {
      const preventDefaultLine = entry.preventDefault
        ? "\n      preventDefault: true,"
        : "";

      return `    "${entry.id}": {
      id: "${entry.id}",
      event: "${entry.event}",
      actionId: "${entry.actionId}",
      chunk: "${entry.chunk}",
      handlerExport: "${entry.handlerExport}",${preventDefaultLine}
    }`;
    })
    .join(",\n");

  const listEntries = [...lists]
    .sort((a, b) => a.listId.localeCompare(b.listId))
    .map(
      (entry) => `    "${entry.listId}": {
      listId: "${entry.listId}",
      keyAttr: "${entry.keyAttr}",
    }`,
    )
    .join(",\n");

  return `{
  events: {
${eventEntries}
  },
  lists: {
${listEntries}
  },
}`;
}

export function buildBindingMapModuleSource(
  options: BindingMapModuleSourceOptions,
): string {
  const bindingMapSource = renderBindingMapObjectLiteralSource(
    options.events,
    options.lists,
  );

  return `import type { BindingMap } from "${options.bindingMapImportPath}";

// This file is auto-generated by ${options.generatedBy}
// Do not edit by hand.

export const ${options.bindingMapConstName}: BindingMap = ${bindingMapSource};

export function ${options.bindingMapBuilderName}(): BindingMap {
  return ${options.bindingMapConstName};
}
`;
}

export function buildCompiledViewModuleSource(
  options: CompiledViewModuleSourceOptions,
): string {
  const viewPascal = toPascalCase(options.fileBasename);
  const viewCamel = toCamelCase(options.fileBasename);
  const artifactName = `${viewCamel}CompiledArtifact`;
  const renderFnName = `render${viewPascal}CompiledView`;
  const bindingFnName = `build${viewPascal}CompiledBindingMap`;

  const bindingInference = options.bindingInference;
  const inferActionId =
    bindingInference?.inferActionId ??
    ((bindingId: string) => toCamelCase(bindingId));
  const inferHandlerExport =
    bindingInference?.inferHandlerExport ??
    ((bindingId: string) => `on${toPascalCase(bindingId)}`);
  const shouldPreventDefault =
    bindingInference?.shouldPreventDefault ??
    ((_bindingId: string, event: BindingEvent) => event === "submit");
  const listKeyAttr = bindingInference?.listKeyAttr ?? "data-hx-key";

  const events: BindingMapEventEntry[] = Array.from(
    options.compiled.bindings.entries(),
  ).map(([id, event]) => ({
    id,
    event,
    actionId: inferActionId(id),
    chunk: bindingInference?.actionChunkPath ?? "/client/actions.js",
    handlerExport: inferHandlerExport(id),
    preventDefault: shouldPreventDefault(id, event),
  }));

  const lists: BindingMapListEntry[] = options.compiled.lists.map((listId) => ({
    listId,
    keyAttr: listKeyAttr,
  }));

  const bindingMapSource = renderBindingMapObjectLiteralSource(events, lists);

  const patchesSource = options.compiled.patches
    .map((patch) => {
      const shared = [
        `      kind: "${patch.kind}",`,
        `      token: ${JSON.stringify(patch.token)},`,
        `      targetId: ${JSON.stringify(patch.targetId)},`,
      ];

      if (patch.kind === "attr") {
        shared.push(`      attrName: ${JSON.stringify(patch.attrName ?? "")},`);
      }

      shared.push(
        `      evaluate: (${options.propsIdentifier}: any) => (${patch.expressionSource}),`,
      );

      return `    {\n${shared.join("\n")}\n    }`;
    })
    .join(",\n");

  return `import type { BindingMap } from "${options.bindingMapTypeImportPath}";
import {
  renderCompiledView,
  type CompiledViewArtifact,
} from "${options.viewCompilerImportPath}";

const compiledBindingMap: BindingMap = ${bindingMapSource};

export const ${artifactName}: CompiledViewArtifact<any> = {
  template: ${JSON.stringify(options.compiled.template)},
  patches: [
${patchesSource}
  ],
  bindingMap: compiledBindingMap,
};

export function ${renderFnName}(${options.propsIdentifier}: any): string {
  return renderCompiledView(${artifactName}, ${options.propsIdentifier});
}

export function ${bindingFnName}(): BindingMap {
  return compiledBindingMap;
}

export const ${viewCamel}CompiledPatchTable = ${artifactName}.patches;
`;
}
