import type { BindingMap } from "../../helix/index.js";

// This file is auto-generated by src/example/scripts/generate-binding-map.ts
// Do not edit by hand.

export const appBindingMap: BindingMap = {
  events: {
    "app-nav": {
      id: "app-nav",
      event: "click",
      actionId: "navigate",
      chunk: "/client/actions.js",
      handlerExport: "onAppNavigate",
      preventDefault: true,
    },
    "create-post": {
      id: "create-post",
      event: "submit",
      actionId: "createPost",
      chunk: "/client/actions.js",
      handlerExport: "onCreatePost",
    },
    "create-user": {
      id: "create-user",
      event: "submit",
      actionId: "createUser",
      chunk: "/client/actions.js",
      handlerExport: "onCreateUser",
    },
    "external-detail-close": {
      id: "external-detail-close",
      event: "click",
      actionId: "external-detail",
      chunk: "/client/actions.js",
      handlerExport: "onExternalDetailClose",
    },
    "external-detail-open": {
      id: "external-detail-open",
      event: "click",
      actionId: "external-detail",
      chunk: "/client/actions.js",
      handlerExport: "onExternalDetailOpen",
    },
    "external-page-next": {
      id: "external-page-next",
      event: "click",
      actionId: "external-page",
      chunk: "/client/actions.js",
      handlerExport: "onExternalPageNext",
    },
    "external-page-prev": {
      id: "external-page-prev",
      event: "click",
      actionId: "external-page",
      chunk: "/client/actions.js",
      handlerExport: "onExternalPagePrev",
    },
    "load-users-panel": {
      id: "load-users-panel",
      event: "click",
      actionId: "loadUsersPanel",
      chunk: "/client/actions.js",
      handlerExport: "onLoadUsersPanel",
    },
    "page-next": {
      id: "page-next",
      event: "click",
      actionId: "setPage",
      chunk: "/client/actions.js",
      handlerExport: "onNextPage",
    },
    "page-prev": {
      id: "page-prev",
      event: "click",
      actionId: "setPage",
      chunk: "/client/actions.js",
      handlerExport: "onPrevPage",
    },
    "posts-page-next": {
      id: "posts-page-next",
      event: "click",
      actionId: "posts-page",
      chunk: "/client/actions.js",
      handlerExport: "onPostsPageNext",
    },
    "posts-page-prev": {
      id: "posts-page-prev",
      event: "click",
      actionId: "posts-page",
      chunk: "/client/actions.js",
      handlerExport: "onPostsPagePrev",
    },
    "sort-email": {
      id: "sort-email",
      event: "click",
      actionId: "setSort",
      chunk: "/client/actions.js",
      handlerExport: "onSortByEmail",
    },
    "sort-name": {
      id: "sort-name",
      event: "click",
      actionId: "setSort",
      chunk: "/client/actions.js",
      handlerExport: "onSortByName",
    }
  },
  lists: {
    "external-products-body": {
      listId: "external-products-body",
      keyAttr: "data-hx-key",
    },
    "posts-body": {
      listId: "posts-body",
      keyAttr: "data-hx-key",
    },
    "trial-dnd-list": {
      listId: "trial-dnd-list",
      keyAttr: "data-hx-key",
    },
    "users-body": {
      listId: "users-body",
      keyAttr: "data-hx-key",
    }
  },
};

export function buildAppBindingMap(): BindingMap {
  return appBindingMap;
}
